site_name: GenAI Tutorials
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: deep orange
    accent: red
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: deep orange
    accent: red
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  font:
    text: Ubuntu
  icon:
    logo: material/robot-happy
  favicon: assets/images/favicon.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
plugins:
  - search
  - privacy
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/subhadeepmandal2000/
    - icon: fontawesome/brands/github
      link: https://github.com/subhadeep0506
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/subhadeepmandal2000/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/subhadeepmandal
copyright: >
  Copyright &copy; 2024 - 2024 Subhadeep Mandal & Sukanya Bag -
  <a href="#__consent">Change cookie settings</a>